#!/usr/bin/env bash
# This is displaying home directory, username and user id

IFS ":"

while read -r username uid home; do
    echo "Username: $username"
    echo "User ID: $uid"
    echo "Home Directory: $home"
done < /etc/passwd
