#!/usr/bin/env bash
#This will print "Best School" 10 times while changing the 4th loop to "bad luck" and the 8th loop to "good luck".
counter=1
while [[ $counter -le 10 ]]; do
	if [ $counter -eq 4 ];
	then
		echo "bad luck"
	elif [ $counter -eq 8 ];
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	((counter++))
done
