#!/usr/bin/env bash
#This prints number 1-20 with a while loop using a case statment to display other items.
counter=1
while [ $counter -le 20 ]; do
	echo $counter

	case $counter in
		4)
			echo "bad luck from China"
			;;
		9)
			echo "bad luck from Japan"
			;;
		17)
			echo "bad luck from Italy"
			;;
	esac
	((counter++))
done
