#!/usr/bin/env bash
# This will give information about the school file empty/exsits etc.
file=school
if [ -e $file ]
then
	echo "school file exists"
if [ -s $file ]
then
	echo "school file is not empty"
	else
	echo "school file is empty"
fi
if [ -f  $file ]
then
	echo "school is a regular file"
fi
else
	echo "school file does not exist"
fi
